exports.countriesGiveSms = [
    { Service: "ru", title: "Russia" },
    { Service: "ukr", title: "Ukraine" },
    { Service: "kazakhstan", title: "Kazakhstan" },
    { Service: "england", title: "England" },
    { Service: "canada", title: "Canada" },
    { Service: "germany", title: "Germany" },
    { Service: "usavirt", title: "USA (Virtual)" },
    { Service: "brazil", title: "Brazil" },
    { Service: "estonia", title: "Estonia" },
    { Service: "france", title: "France" },
    { Service: "indonesia", title: "Indonesia" },
    { Service: "kyrgyzstan", title: "Kyrgyzstan" },
    { Service: "laos", title: "Laos" },
    { Service: "lithuania", title: "Lithuania" },
    { Service: "netherlands", title: "Netherlands" },
    { Service: "poland", title: "Poland" },
    { Service: "romania", title: "Romania" },
    { Service: "sweden", title: "Sweden" },
    { Service: "indiia", title: "India" },
    { Service: "malaiziia", title: "Malaysia" },
    { Service: "vetnam", title: "Vietnam" },
    { Service: "filippiny", title: "Philippines" },
    { Service: "turtsiia", title: "Turkey" },
    { Service: "moldova", title: "Moldova" },
    { Service: "uzbekistan", title: "Uzbekistan" },
    { Service: "gruziia", title: "Georgia" },
    { Service: "irlandiia", title: "Ireland" },
    { Service: "portugaliia", title: "Portugal" },
    { Service: "ispaniia", title: "Spain" },
    { Service: "chekhiia", title: "Czech Republic" },
    { Service: "bangladesh", title: "Bangladesh" },
    { Service: "ssha", title: "USA" },
    { Service: "gonkong", title: "Hong Kong" },
    { Service: "tailand", title: "Thailand" },
    { Service: "meksika", title: "Mexico" },
    { Service: "latviia", title: "Latvia" },
    { Service: "pakistan", title: "Pakistan" },
    { Service: "gretsiia", title: "Greece" },
    { Service: "nikaragua", title: "Nicaragua" },
    { Service: "argentina", title: "Argentina" },
    { Service: "gaiti", title: "Haiti" },
    { Service: "mongoliia", title: "Mongolia" },
    { Service: "izrail", title: "Israel" },
    { Service: "egipet", title: "Egypt" },
    { Service: "gvatemala", title: "Guatemala" },
    { Service: "liviia", title: "Libya" },
    { Service: "iran", title: "Iran" },
    { Service: "iemen", title: "Yemen" },
    { Service: "tadzhikistan", title: "Tajikistan" },
    { Service: "kitai", title: "China" },
    { Service: "shrilanka", title: "Sri Lanka" },
    { Service: "siriia", title: "Syria" },
    { Service: "livan", title: "Lebanon" },
    { Service: "boliviia", title: "Bolivia" },
    { Service: "serbiia", title: "Serbia" },
    { Service: "kolumbiia", title: "Colombia" },
    { Service: "avstriia", title: "Austria" },
    { Service: "alzhir", title: "Algeria" },
    { Service: "peru", title: "Peru" },
    { Service: "gonduras", title: "Honduras" },
    { Service: "marokko", title: "Morocco" },
    { Service: "venesuela", title: "Venezuela" },
    { Service: "nigeriia", title: "Nigeria" },
    { Service: "iamaika", title: "Jamaica" },
    { Service: "salvador", title: "El Salvador" },
    { Service: "botsvana", title: "Botswana" },
    { Service: "paragvai", title: "Paraguay" },
    { Service: "nepal", title: "Nepal" },
    { Service: "uganda", title: "Uganda" },
    { Service: "irak", title: "Iraq" },
    { Service: "iordaniia", title: "Jordan" },
    { Service: "mianma", title: "Myanmar" },
    { Service: "demkongo", title: "Democratic Congo" },
    { Service: "keniia", title: "Kenya" },
    { Service: "kambodzha", title: "Cambodia" },
    { Service: "belarus", title: "Belarus" },
    { Service: "kotdivuar", title: "Ivory Coast" },
    { Service: "saudaraviia", title: "Saudi Arabia" },
    { Service: "oae", title: "UAE" },
    { Service: "khorvatiia", title: "Croatia" },
    { Service: "papuanovaiagvineia", title: "Papua New Guinea" },
    { Service: "tanzaniia", title: "Tanzania" },
    { Service: "gvineia", title: "Guinea" },
    { Service: "mali", title: "Mali" },
    { Service: "kamerun", title: "Cameroon" },
    { Service: "mavritaniia", title: "Mauritania" },
    { Service: "serraleone", title: "Sierra Leone" },
    { Service: "burkinafaso", title: "Burkina Faso" },
    { Service: "daniia", title: "Denmark" },
    { Service: "tunis", title: "Tunisia" },
    { Service: "dominikanskaiarespublika", title: "Dominican Republic" },
    { Service: "iuzhnaiaafrika", title: "South Africa" },
    { Service: "ekvador", title: "Ecuador" },
    { Service: "liberiia", title: "Liberia" },
    { Service: "senegal", title: "Senegal" },
    { Service: "afganistan", title: "Afghanistan" },
    { Service: "novaiazelandiia", title: "New Zealand" },
    { Service: "chad", title: "Chad" },
    { Service: "angola", title: "Angola" },
    { Service: "gana", title: "Ghana" },
    { Service: "iuzhnaiakoreia", title: "South Korea" },
    { Service: "sudan", title: "Sudan" },
    { Service: "taivan", title: "Taiwan" },
    { Service: "zimbabve", title: "Zimbabwe" },
    { Service: "turkmenistan", title: "Turkmenistan" },
    { Service: "reiunon", title: "Reunion" },
    { Service: "kipr", title: "Cyprus" },
    { Service: "gaiana", title: "Guyana" },
    { Service: "maldivy", title: "Maldives" },
    { Service: "mozambik", title: "Mozambique" },
    { Service: "gambiia", title: "Gambia" },
    { Service: "trinidaditobago", title: "Trinidad and Tobago" },
    { Service: "gabon", title: "Gabon" },
    { Service: "brunei", title: "Brunei" },
    { Service: "butan", title: "Bhutan" },
    { Service: "surinam", title: "Surititle" },
    { Service: "armeniia", title: "Armenia" },
    { Service: "benin", title: "Benin" },
    { Service: "mavrikii", title: "Mauritius" },
    { Service: "fidzhi", title: "Fiji" },
    { Service: "kongo", title: "Congo" },
    { Service: "dominika", title: "Dominica" },
    { Service: "bermudy", title: "Bermuda" },
    { Service: "aruba", title: "Aruba" },
    { Service: "chili", title: "Chile" },
    { Service: "finliandiia", title: "Finland" },
    { Service: "italiia", title: "Italy" },
    { Service: "bolgariia", title: "Bulgaria" },
    { Service: "vengriia", title: "Hungary" },
    { Service: "sloveniia", title: "Slovenia" },
    { Service: "norvegiia", title: "Norway" }
];

exports.platformsGiveSms = {
"ai": "CELEBE",
"do": "Leboncoin",
"dh": "eBay",
"sk": "Skroutz",
"lq": "Potato",
"mh": "Auchan",
"wv": "AIS",
"i": "Socios",
"bf": "Keybase",
"mm": "Microsoft",
"qd": "Taobao",
"at": "Perfluence",
"qf": "RedBook",
"dp": "ProtonMail",
"mi": "Zupee",
"yb": "Rent+",
"wa": "Whatsapp",
"uz": "OffGamers",
"ou": "Gabi",
"he": "Mewt",
"jj": "Aitu",
"ez": "GoerliFaucet",
"ts": "PayPal",
"ta": "Wink",
"qt": "MoneyControl",
"ef": "Nextdoor",
"ad": "Iti",
"cg": "Gemgala",
"nu": "Stripe",
"rf": "Akudo",
"kj": "YAPPY",
"ul": "Get it",
"nv": "Naver",
"fw": "99acres",
"ud": "Disney Hotstar",
"lw": "MrGreen",
"io": "ZdravCity",
"oy": "CashFly",
"qm": "RosaKhutor",
"mn": "RRSA",
"dt": "Delivery Club",
"lt": "BitClout",
"ui": "RuTube",
"qw": "Kiwi",
"fj": "Potato Chat",
"tx": "Bolt",
"kc": "Vinted",
"xd": "Tokopedia",
"p.p.": "Huya",
"qj": "Whoosh",
"qh": "Oriflame",
"jt": "Turkish Petroleum",
"ok": "Ok.ru",
"wk": "Mobile01",
"bn": "Alfagift",
"wh": "TanTan",
"vm": "OkCupid",
"ri": "BillMill",
"bs": "TradeUP",
"tw": "Twitter",
"ey": "Miloan",
"je": "Nanovest",
"hr": "JKF",
"kn": "Verse",
"yf": "Citymobil",
"aj": "OneAset",
"bx": "Dosi",
"ca": "SuperS",
"gr": "Astropay",
"rv": "Kotak811",
"bp": "GoFundMe",
"ni": "Gojek",
"fy": "Mylove",
"dk": "Pairs",
"bk": "G2G",
"bb": "LazyPay",
"vo": "Brand20ua",
"bh": "Uteka",
"gz": "LYKA",
"ww": "BIP",
"ur": "MyDailyCash",
"cx": "Icrypex",
"sh": "VkusVill",
"gv": "Humta",
"ve": "Dream11",
"kp": "HQ Trivia",
"uf": "Eneba",
"aa": "Probo",
"tk": "MVideo",
"iq": "Icq",
"ej": "MrQ",
"ss": "Hezzl",
"sf": "SneakersnStuff",
"ce": "Moscow",
"dc": "YikYak",
"sl": "SberApteka",
"dl": "Lazada",
"uo": "CafeBazaar",
"uh": "Yubo",
"pl": "Crossroads",
"dg": "Mercari",
"cb": "Basos",
"p.u.": "JustDating",
"gh": "GyFTR",
"ev": "Picpay",
"qg": "MoneyPay",
"bw": "Signal",
"cc": "Quipp",
"jf": "Likee",
"e.q.": "Qoo10",
"dd": "CloudChat",
"jc": "IVI",
"er": "Kwork",
"ip": "Burger King",
"bu": "MonobankIndia",
"nq": "Trip",
"qi": "23red",
"e.g.": "ContactSys",
"cp": "Uklon",
"sg": "OZON",
"xr": "Tango",
"uk": "Airbnb",
"ko": "AdaKami",
"nf": "Netflix",
"vy": "Meta",
"dy": "Zomato",
"ha": "My11Circle",
"tg": "Telegram",
"dq": "IceCasino",
"r": "Lotus",
"bc": "GCash",
"ne": "Coindcx",
"mr": "Fastmail",
"we": "FriendAround",
"ry": "McDonalds",
"qa": "MyFishka",
"p.m.": "AOL",
"la": "Ssoidnet",
"ak": "Douyu",
"go": "Google, YouTube, Gmail",
"oh": "Tinder",
"dn": "Paxful",
"xl": "Wmaraci",
"vz": "Hinge",
"rd": "Lenta",
"wb": "WeChat",
"ew": "Nike",
"gm": "Mocospace",
"wj": "1xbet",
"xe": "GalaxyChat",
"sn": "OLX",
"ae": "MyGLO",
"ch": "Pocket52",
"py": "Monese",
"hn": "1688",
"qy": "Zhihu",
"ck": "BeReal",
"kw": "Foody",
"ml": "ApostaGanha",
"ci": "RedBus",
"wc": "Craigslist",
"p.d.": "IFood",
"be": "SberMegaMarket",
"xy": "Depop",
"cf": "Irancell",
"wp": "163COM",
"rx": "Sheerid",
"su": "LOCO",
"ho": "Cathay",
"af": "GalaxyWin",
"bq": "Adani",
"oq": "Vlife",
"en": "HOP",
"om": "Corona",
"sb": "Lamoda",
"ig": "Instagram",
"uj": "Champion Casino",
"mu": "MyMusicTaste",
"cq": "Mercado",
"ti": "Cryptocom",
"uu": "Wildberries",
"ub": "Uber",
"ln": "Grocers",
"me": "Line msg",
"of": "Urent",
"fz": "KFC",
"un": "Humblebundle",
"ug": "Fiqsy",
"kr": "Eyecon",
"vn": "Yaay",
"qe": "GG",
"ds": "Discord",
"ggg": "PagSmile",
"uw": "Kirana",
"vs": "WinzoGame",
"gt": "Gett",
"uy": "Meliuz",
"hq": "Magicbricks",
"im": "Imo",
"bv": "Metro",
"po": "Premium.one",
"jg": "Grab",
"es": "IQIYI",
"bo": "Wise",
"kb": "Kufarby",
"wq": "Leboncoin1",
"jh": "PingPong",
"tt": "Ziglu",
"rrr": "Wolt",
"ih": "TeenPattiStarpro",
"od": "FWDMAX",
"iv": "Inboxlv",
"xh": "OVO",
"ra": "KeyPay",
"bz": "Blizzard",
"rc": "Skype",
"pt": "Bitaqaty",
"gu": "Fora",
"ma": "Mail.ru",
"ji": "Monobank",
"op": "MIRATORG",
"hk": "4Fun",
"gp": "Ticketmaster",
"up": "Magnolia",
"dr": "OpenAI",
"bd": "X5ID",
"gl": "GlobalTel",
"gx": "Hepsiburada.com",
"ay": "Ruten",
"sr": "Starbucks",
"pa": "Gamekit",
"ct": "KitchenInTheNeighborhood",
"ht": "Bitso",
"ft": "Bookmakers",
"ka": "Shopee",
"mx": "SoulApp",
"wt": "IZI",
"sw": "NCsoft",
"ep": "Temu",
"mc": "Michat",
"qr": "MEGA",
"ee": "Twilio",
"le": "E bike games",
"ec": "RummyCulture",
"qu": "Agroinform",
"oh": "MapleSEA",
"fa": "XadrezFeliz",
"cm": "Prom",
"bt": "Alfa",
"ya": "Yandex",
"ot": "Any other",
"cj": "Dotz",
"hh": "Uplay",
"gc": "TradingView",
"sm": "YoWin",
"ki": "99app",
"you": "Lyft",
"de": "Carousel",
"pq": "CDkeys",
"fm": "Touchance",
"lr": "Okta",
"ly": "Olacabs",
"va": "SportGully",
"df": "Happn",
"kf": "Weibo",
"vc": "Banqi",
"fk": "BLIBLI",
"xn": "Family",
"th": "WestStein",
"fs": "Şikayet var",
"rz": "EasyPay",
"cn": "Fiverr",
"dx": "Powercredit",
"pg": "NRJ Music Awards",
"bg": "MIXMART",
"mj": "Zalo",
"xw": "Taki",
"ua": "BlaBlaCar",
"pf": "Pof.com",
"an": "Adidas",
"mk": "LongHu",
"lh": "24betting",
"hg": "Switips",
"sq": "KuCoinPlay",
"lx": "DewuPoison",
"gf": "Google Voice",
"iy": "FoodHub",
"nz": "Foodpanda",
"ah": "EscapeFromTarkov",
"nw": "Ximalaya",
"sj": "HandyPick",
"et": "Clubhouse",
"tl": "Truecaller",
"md": "Banks",
"co": "Rediffmail",
"ga": "Roposo",
"oc": "DealShare",
"og": "Okko",
"r.h.": "Ace2Three",
"rl": "InDriver",
"dj": "LUKOIL-AZS",
"pr": "Trendyol",
"bj": "Vita Express",
"rk": "Photo",
"ao": "UU163",
"nr": "Tosla",
"ph": "SnappFood",
"ar": "Wondermart",
"ij": "Revolut",
"qc": "Primaries 2020",
"gd": "Survey time",
"ky": "SpatenOktoberfest",
"sp": "HappyFresh",
"xj": "SberMarket",
"ac": "DoorDash",
"ba": "Expressmoney",
"kz": "NimoTV",
"np": "Siply",
"vf": "Q12 Trivia",
"tf": "Noon",
"from": "Global24",
"jz": "Kaya",
"yd": "Mihuashi's Confucianism",
"cl": "UWIN",
"fx": "PGbonus",
"jr": "Scooter",
"px": "Nifty",
"nl": "Myntra",
"tn": "LinkedIN",
"dw": "Divar",
"ke": "El Dorado",
"ku": "RoyalWin",
"el": "Bisu",
"bm": "MarketGuru",
"n.n.": "Giftcloud",
"lp": "Algida",
"eo": "Sizeer",
"cw": "PaddyPower",
"gw": "CallApp",
"wo": "Parkplus",
"si": "Cita Previa",
"xt": "Flipkart",
"wx": "Apple",
"qz": "Faceit",
"di": "Loanflix",
"kx": "Vivo",
"nb": "Loyal",
"xi": "InFund",
"pw": "SellMonitor",
"fb": "Facebook",
"ex": "Linode",
"st": "Auchan",
"mt": "Steam",
"av": "Avito",
"db": "Ezbuy",
"wn": "GameArena",
"sa": "AGIBANK",
"re": "Coinbase",
"no": "Virgo",
"ls": "Careem",
"ql": "CMTcuzdan",
"tm": "Akulaku",
"rb": "Tick",
"ei": "Taksheel",
"hc": "MOMO",
"qk": "Bit",
"gs": "Samsung Shop",
"lf": "TikTok/Douyin",
"vd": "Betfair",
"so": "RummyWealth",
"wl": "YouGotaGift",
"yx": "JTExpress",
"vj": "Stormgain",
"sv": "Delivery",
"ob": "Onlinerby",
"rp": "Hamrahaval",
"tc": "Rambler",
"vx": "HeyBox",
"ab": "Alibaba",
"eh": "Telegram 2.0",
"jm": "Mzadqatar",
"fo": "MobiKwik",
"az": "CityBase",
"ny": "Pyro Music",
"xu": "RecargaPay",
"yk": "SportMaster",
"zw": "Quack",
"lv": "Megogo",
"fh": "Lalamove",
"yes": "Weverse",
"xq": "MPL",
"lc": "Subito",
"ea": "JamesDelivery",
"qn": "Blued",
"ib": "Immovable property",
"wg": "Skout",
"ff": "AVON",
"jx": "Swiggy",
"au": "Haraj",
"uv": "BinBin",
"eb": "Voltz",
"ju": "Indomaret",
"kt": "KakaoTalk",
"km": "Rozetka",
"yg": "CourseHero",
"cd": "SpotHit",
"xk": "DiDi",
"qo": "Moneylion",
"sd": "Dodopizza",
"fe": "CliQQ",
"ed": "Gamer",
"bi": "Author: Ys4fun",
"yz": "Near",
"xf": "LightChat",
"tj": "DbrUA",
"mf": "Weidian",
"rg": "Porbet",
"xv": "Wish",
"mb": "Yahoo",
"mg": "Magnet",
"gi": "Hotline",
"hm": "Globus",
"ol": "KazanExpress",
"xb": "RummyOla",
"vk": "Vkontakte",
"hw": "Alipay/Alibaba",
"oz": "Poshmark",
"tq": "Swvl",
"fc": "PharmEasy",
"ue": "Onet",
"aq": "Glovo",
"mq": "GMNG",
"my": "CAIXA",
"vw": "CoinField",
"dm": "Iwplay",
"fg": "Indian Oil",
"xs": "GroupMe",
"hx": "AliExpress",
"yj": "EWallet",
"eu": "LiveScore",
"cy": "RSA",
"us": "IRCTC",
"br": "Tasty and Tochka",
"jb": "Wing Money",
"fl": "RummyLoot",
"fr": "Dana",
"aw": "Taikang",
"zh": "Zoho",
"zj": "ROBINHOOD",
"zi": "LoveLocal",
"yp": "Payzapp",
"zd": "Zilch",
"yo": "Amasia",
"zs": "Bilibili",
"zm": "OfferUp",
"yw": "Grindr",
"yy": "Venmo",
"zl": "Airtel",
"yl": "Yalla",
"zn": "Biedronka",
"fv": "Video",
"fu": "Snapchat",
"cr": "TenChat",
"hi": "JungleeRummy",
"nk": "Gittigidiyor",
"vv": "Seosprint",
"dv": "NoBroker",
"h": "Band",
"ll": "888casino",
"hb": "Twitch",
"vp": "Kwai",
"td": "ChaingeFinance",
"xz": "Paycell",
"li": "Baidu",
"lj": "Santander",
"xx": "Joyride",
"yq": "Foxtrot",
"mo": "Bumble",
"ge": "Paytm",
"lb": "Mailru Group",
"zq": "IndiaPlays",
"ik": "GuruBets",
"cu": "炙热星河",
"oe": "Codashop",
"kh": "Bukalapak",
"sy": "Brahma",
"vi": "Viber",
"os": "Dhani",
"uc": "Tatneft",
"ym": "Yula",
"r.m.": "Faberlic",
"cv": "WashXpress",
"pz": "Lidl",
"kl": "Kolesa.kz",
"gj": "Carousel",
"zf": "OnTaxi",
"gb": "YouStar",
"en": "Hermes",
"jl": "Hopi",
"hy": "Ininal",
"ax": "CrefisaMais",
"iu": "Bykea",
"fi": "Dundle",
"gk": "AptekaRU",
"rt": "Hily",
"cz": "Getmega",
"dz": "Domino's Pizza",
"fd": "Mamba",
"kg": "FreeChargeApp",
"il": "IQOS",
"hz": "Drom",
"xm": "Letual",
"qq": "Tencent QQ",
"tp": "IndiaGold",
"am": "Amazon",
"qb": "Payberry",
"hu": "Ukrnet",
"em": "ZéDelivery",
"vg": "ShellBox",
"tr": "Paysend",
"cs": "AgriDevelop",
"lk": "PurePlatfrom",
"rj": "Children's world",
"wf": "YandexGo",
"zu": "BigC",
"jq": "Paysafecard",
"nm": "This shop",
"bl": "BIGO LIVE",
"sz": "Pivko24",
"hj": "Stoloto",
"yes": "MTS CashBack",
"du": "AUBANK",
"yn": "Allegro",
"zo": "Kaggle",
"zv": "Digital",
"yu": "Xiaomi",
"yv": "IPLwin",
"zg": "Setel",
"yi": "Yemeksepeti",
"zk": "Deliveroo",
"zt": "Budweiser",
"zr": "Papara",
"zz": "Dent",
"zx": "Community Gaming",
"zy": "Nttgame",
"ys": "ZCity",
"for": "JDcom",
"call": "Receiving a call-drop"
};
